/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef helloworld_TYPES_H
#define helloworld_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace hellons {

class response;

typedef struct _response__isset {
  _response__isset() : document(false), cache_hit_flag(false) {}
  bool document :1;
  bool cache_hit_flag :1;
} _response__isset;

class response {
 public:

  response(const response&);
  response& operator=(const response&);
  response() : document(), cache_hit_flag(0) {
  }

  virtual ~response() throw();
  std::string document;
  int32_t cache_hit_flag;

  _response__isset __isset;

  void __set_document(const std::string& val);

  void __set_cache_hit_flag(const int32_t val);

  bool operator == (const response & rhs) const
  {
    if (!(document == rhs.document))
      return false;
    if (!(cache_hit_flag == rhs.cache_hit_flag))
      return false;
    return true;
  }
  bool operator != (const response &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const response & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(response &a, response &b);

inline std::ostream& operator<<(std::ostream& out, const response& obj)
{
  obj.printTo(out);
  return out;
}

} // namespace

#endif
