/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "HTTPproxy_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace HTTPproxy {


response::~response() throw() {
}


void response::__set_document(const std::string& val) {
  this->document = val;
}

void response::__set_cache_hit_flag(const int32_t val) {
  this->cache_hit_flag = val;
}

uint32_t response::read(::apache::thrift::protocol::TProtocol* iprot) {

  apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->document);
          this->__isset.document = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->cache_hit_flag);
          this->__isset.cache_hit_flag = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t response::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("response");

  xfer += oprot->writeFieldBegin("document", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->document);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("cache_hit_flag", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->cache_hit_flag);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(response &a, response &b) {
  using ::std::swap;
  swap(a.document, b.document);
  swap(a.cache_hit_flag, b.cache_hit_flag);
  swap(a.__isset, b.__isset);
}

response::response(const response& other0) {
  document = other0.document;
  cache_hit_flag = other0.cache_hit_flag;
  __isset = other0.__isset;
}
response& response::operator=(const response& other1) {
  document = other1.document;
  cache_hit_flag = other1.cache_hit_flag;
  __isset = other1.__isset;
  return *this;
}
void response::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "response(";
  out << "document=" << to_string(document);
  out << ", " << "cache_hit_flag=" << to_string(cache_hit_flag);
  out << ")";
}

} // namespace
