/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "HTTPproxy_constants.h"

namespace HTTPproxy {

const HTTPproxyConstants g_HTTPproxy_constants;

HTTPproxyConstants::HTTPproxyConstants() {
}

} // namespace

